### ISSUE TITLE
Difference with hangyas/TelegramBot

### ISSUE THREAD

**Issue by spalladino** [greyblake/crystal-telegram_bot#1]
Hey! I was looking for Telegram bot API libs for Crystal, and stumbled upon both this library and https://github.com/hangyas/TelegramBot, and noted that they are entirely different efforts. Mind if I ask you what are the differences between this one and the one from hangyas, and what was the motivation for writing a new one? Thank you!

**Comment by greyblake** [comment]
Hi! To be honest, I didn't find his lib, when I was searching for something like this.
I just needed to create a simple bot, and I've extracted my stuff into this library.
I recommend you to use hangyas's lib, because loooks like it supports most of the Telegram features.
I'll also give it a try, and if I like it, I'll close the project.

Thanks!
